/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.event.ActionListener;
import javax.swing.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Scanner;
import javax.swing.ImageIcon;
import java.awt.event.*;
import java.awt.*;
import java.io.*;
import java.io.FileWriter;
/**
 *
 * @author User
 */
public class GUI extends javax.swing.JFrame {
    
    static user[] user_card;
    static int totalUser;
    static int userNo,transac_type;
    static double panel = 0; 
    static user current_user;
    static user recipient;
    static double balance;
    static double transac_amount=0;
    static double amtTransfer;
    static String transac_id,transac_date,recipient_name;
    static Transaction tranc = new Transaction();
    static DecimalFormat df = new DecimalFormat("$0.00");
    static JOptionPane frame = new JOptionPane();
/* 0 = MENU; 1=WITHDRAW; 2=DEPOSIT; 3=TRANSFER; 4=BALANCE; 5=RECEIPT*/
/* 1.1 WITHDRAW PROGRESS */
    
    private Timer t;
    private ActionListener al;
    
    
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    public GUI(user[]user_card,int userNo,int totalUser){
        this.totalUser=totalUser;
        this.user_card = user_card;
        current_user= user_card[userNo];
        initComponents(); 
        
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public void switchPanels(JPanel pane){
        layeredPane.removeAll();
        layeredPane.add(pane);
        layeredPane.repaint();
        layeredPane.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Keypad = new javax.swing.JPanel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnEmpty = new javax.swing.JButton();
        btnDoubleZero = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        layeredPane = new javax.swing.JLayeredPane();
        MENU = new javax.swing.JPanel();
        btnBalance = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        WITHDRAW = new javax.swing.JPanel();
        titleWithdraw = new javax.swing.JTextField();
        RM = new javax.swing.JTextField();
        amountWithdraw = new javax.swing.JTextField();
        RM6 = new javax.swing.JTextField();
        DEPOSIT1 = new javax.swing.JPanel();
        titleDeposit = new javax.swing.JTextField();
        RM1 = new javax.swing.JTextField();
        amountDeposit = new javax.swing.JTextField();
        RM5 = new javax.swing.JTextField();
        BALANCE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showAccNo = new javax.swing.JTextField();
        showBalance = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TRANSFERACC = new javax.swing.JPanel();
        titleTransfer = new javax.swing.JLabel();
        accP1 = new javax.swing.JTextField();
        AskReceipt = new javax.swing.JPanel();
        NoReceipt = new javax.swing.JRadioButton();
        Receipt = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        TRANSFERAMT = new javax.swing.JPanel();
        RM2 = new javax.swing.JTextField();
        amountTransfer = new javax.swing.JTextField();
        RM7 = new javax.swing.JTextField();
        titleTransfer1 = new javax.swing.JLabel();
        CONFIRMATION = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        displayCardHolder = new javax.swing.JTextField();
        displayCardNo = new javax.swing.JTextField();
        displayTransferAmt = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        PROCESSING = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu\n");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
                none(evt);
            }
        });

        Keypad.setBackground(new java.awt.Color(140, 118, 165));
        Keypad.setPreferredSize(new java.awt.Dimension(360, 360));

        btnOne.setBackground(new java.awt.Color(213, 221, 222));
        btnOne.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnOne.setForeground(new java.awt.Color(140, 118, 165));
        btnOne.setText("1");
        btnOne.setBorderPainted(false);
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(213, 221, 222));
        btnTwo.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(140, 118, 165));
        btnTwo.setText("2");
        btnTwo.setBorderPainted(false);
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(213, 221, 222));
        btnThree.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnThree.setForeground(new java.awt.Color(140, 118, 165));
        btnThree.setText("3");
        btnThree.setBorderPainted(false);
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(229, 116, 88));
        btnCancel.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(72, 62, 62));
        btnCancel.setText("CANCEL");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(213, 221, 222));
        btnFour.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnFour.setForeground(new java.awt.Color(140, 118, 165));
        btnFour.setText("4");
        btnFour.setBorderPainted(false);
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(213, 221, 222));
        btnFive.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnFive.setForeground(new java.awt.Color(140, 118, 165));
        btnFive.setText("5");
        btnFive.setBorderPainted(false);
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setBackground(new java.awt.Color(213, 221, 222));
        btnSix.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnSix.setForeground(new java.awt.Color(140, 118, 165));
        btnSix.setText("6");
        btnSix.setBorderPainted(false);
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 0));
        btnClear.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(72, 62, 62));
        btnClear.setText("CLEAR");
        btnClear.setBorderPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(213, 221, 222));
        btnSeven.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(140, 118, 165));
        btnSeven.setText("7");
        btnSeven.setBorderPainted(false);
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(213, 221, 222));
        btnNine.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnNine.setForeground(new java.awt.Color(140, 118, 165));
        btnNine.setText("9");
        btnNine.setBorderPainted(false);
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(213, 221, 222));
        btnEight.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnEight.setForeground(new java.awt.Color(140, 118, 165));
        btnEight.setText("8");
        btnEight.setBorderPainted(false);
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyActionPerformed(evt);
            }
        });

        btnDoubleZero.setBackground(new java.awt.Color(213, 221, 222));
        btnDoubleZero.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnDoubleZero.setForeground(new java.awt.Color(140, 118, 165));
        btnDoubleZero.setText("00");
        btnDoubleZero.setBorderPainted(false);
        btnDoubleZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleZeroActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(0, 255, 51));
        btnEnter.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(72, 62, 62));
        btnEnter.setText("ENTER");
        btnEnter.setBorderPainted(false);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(213, 221, 222));
        btnZero.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnZero.setForeground(new java.awt.Color(140, 118, 165));
        btnZero.setText("0");
        btnZero.setBorderPainted(false);
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnDecimal.setBackground(new java.awt.Color(213, 221, 222));
        btnDecimal.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        btnDecimal.setForeground(new java.awt.Color(140, 118, 165));
        btnDecimal.setText(".");
        btnDecimal.setBorderPainted(false);

        javax.swing.GroupLayout KeypadLayout = new javax.swing.GroupLayout(Keypad);
        Keypad.setLayout(KeypadLayout);
        KeypadLayout.setHorizontalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFour, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFive, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSix, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEight, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDoubleZero, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEmpty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        KeypadLayout.setVerticalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoubleZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPane.setLayout(new java.awt.CardLayout());

        MENU.setBackground(new java.awt.Color(255, 239, 239));
        MENU.setPreferredSize(new java.awt.Dimension(476, 256));

        btnBalance.setBackground(new java.awt.Color(193, 112, 142));
        btnBalance.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnBalance.setForeground(new java.awt.Color(255, 255, 255));
        btnBalance.setText("BALANCE");
        btnBalance.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBalance.setBorderPainted(false);
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnWithdraw.setBackground(new java.awt.Color(193, 112, 142));
        btnWithdraw.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        btnWithdraw.setText("WITHDRAW");
        btnWithdraw.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnWithdraw.setBorderPainted(false);
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnDeposit.setBackground(new java.awt.Color(193, 112, 142));
        btnDeposit.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(255, 255, 255));
        btnDeposit.setText("DEPOSIT");
        btnDeposit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnDeposit.setBorderPainted(false);
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnTransfer.setBackground(new java.awt.Color(193, 112, 142));
        btnTransfer.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnTransfer.setForeground(new java.awt.Color(255, 255, 255));
        btnTransfer.setText("TRANSFER");
        btnTransfer.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnTransfer.setBorderPainted(false);
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU);
        MENU.setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENULayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPane.add(MENU, "card2");

        WITHDRAW.setBackground(new java.awt.Color(255, 239, 239));
        WITHDRAW.setPreferredSize(new java.awt.Dimension(476, 256));

        titleWithdraw.setEditable(false);
        titleWithdraw.setBackground(new java.awt.Color(255, 239, 239));
        titleWithdraw.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        titleWithdraw.setForeground(new java.awt.Color(140, 118, 165));
        titleWithdraw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleWithdraw.setText("Please Enter the Amount:");
        titleWithdraw.setBorder(null);
        titleWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleWithdrawActionPerformed(evt);
            }
        });

        RM.setEditable(false);
        RM.setBackground(new java.awt.Color(255, 239, 239));
        RM.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RM.setForeground(new java.awt.Color(140, 118, 165));
        RM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM.setText("RM");
        RM.setBorder(null);
        RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMActionPerformed(evt);
            }
        });

        amountWithdraw.setEditable(false);
        amountWithdraw.setBackground(new java.awt.Color(242, 187, 187));
        amountWithdraw.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        amountWithdraw.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountWithdraw.setBorder(null);
        amountWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountWithdrawActionPerformed(evt);
            }
        });

        RM6.setEditable(false);
        RM6.setBackground(new java.awt.Color(255, 239, 239));
        RM6.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RM6.setForeground(new java.awt.Color(140, 118, 165));
        RM6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RM6.setText(".00");
        RM6.setBorder(null);
        RM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WITHDRAWLayout = new javax.swing.GroupLayout(WITHDRAW);
        WITHDRAW.setLayout(WITHDRAWLayout);
        WITHDRAWLayout.setHorizontalGroup(
            WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WITHDRAWLayout.createSequentialGroup()
                .addGroup(WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WITHDRAWLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(RM, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RM6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WITHDRAWLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(titleWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        WITHDRAWLayout.setVerticalGroup(
            WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WITHDRAWLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(titleWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(WITHDRAWLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(amountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        layeredPane.add(WITHDRAW, "card3");

        DEPOSIT1.setBackground(new java.awt.Color(255, 239, 239));
        DEPOSIT1.setPreferredSize(new java.awt.Dimension(476, 256));

        titleDeposit.setEditable(false);
        titleDeposit.setBackground(new java.awt.Color(255, 239, 239));
        titleDeposit.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        titleDeposit.setForeground(new java.awt.Color(140, 118, 165));
        titleDeposit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleDeposit.setText("Please Enter the Amount:");
        titleDeposit.setBorder(null);
        titleDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleDepositActionPerformed(evt);
            }
        });

        RM1.setEditable(false);
        RM1.setBackground(new java.awt.Color(255, 239, 239));
        RM1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RM1.setForeground(new java.awt.Color(140, 118, 165));
        RM1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM1.setText("RM");
        RM1.setBorder(null);
        RM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM1ActionPerformed(evt);
            }
        });

        amountDeposit.setEditable(false);
        amountDeposit.setBackground(new java.awt.Color(242, 187, 187));
        amountDeposit.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        amountDeposit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountDeposit.setBorder(null);
        amountDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountDepositActionPerformed(evt);
            }
        });

        RM5.setEditable(false);
        RM5.setBackground(new java.awt.Color(255, 239, 239));
        RM5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RM5.setForeground(new java.awt.Color(140, 118, 165));
        RM5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RM5.setText(".00");
        RM5.setBorder(null);
        RM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DEPOSIT1Layout = new javax.swing.GroupLayout(DEPOSIT1);
        DEPOSIT1.setLayout(DEPOSIT1Layout);
        DEPOSIT1Layout.setHorizontalGroup(
            DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSIT1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DEPOSIT1Layout.createSequentialGroup()
                        .addComponent(RM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RM5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        DEPOSIT1Layout.setVerticalGroup(
            DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSIT1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(titleDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        layeredPane.add(DEPOSIT1, "card4");

        BALANCE.setBackground(new java.awt.Color(255, 239, 239));
        BALANCE.setPreferredSize(new java.awt.Dimension(476, 256));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 118, 165));
        jLabel1.setText("Balance     :");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 118, 165));
        jLabel2.setText("Card No.    : ");

        showAccNo.setEditable(false);
        showAccNo.setBackground(new java.awt.Color(242, 187, 187));
        showAccNo.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        showAccNo.setForeground(new java.awt.Color(140, 118, 165));
        showAccNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showAccNo.setBorder(null);
        showAccNo.setCaretColor(new java.awt.Color(255, 255, 255));
        showAccNo.setSelectionColor(new java.awt.Color(153, 153, 255));
        showAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAccNoActionPerformed(evt);
            }
        });

        showBalance.setEditable(false);
        showBalance.setBackground(new java.awt.Color(242, 187, 187));
        showBalance.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        showBalance.setForeground(new java.awt.Color(140, 118, 165));
        showBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showBalance.setBorder(null);
        showBalance.setCaretColor(new java.awt.Color(255, 255, 255));
        showBalance.setSelectionColor(new java.awt.Color(153, 153, 255));
        showBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBalanceActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(242, 187, 187));
        jTextField3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(140, 118, 165));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("RM");
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(140, 118, 165));
        jLabel4.setText("ACCOUNT INFORMATION");

        javax.swing.GroupLayout BALANCELayout = new javax.swing.GroupLayout(BALANCE);
        BALANCE.setLayout(BALANCELayout);
        BALANCELayout.setHorizontalGroup(
            BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BALANCELayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BALANCELayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showBalance))
                    .addComponent(showAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BALANCELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        BALANCELayout.setVerticalGroup(
            BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BALANCELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showAccNo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        layeredPane.add(BALANCE, "card6");

        TRANSFERACC.setBackground(new java.awt.Color(255, 239, 239));
        TRANSFERACC.setPreferredSize(new java.awt.Dimension(476, 256));

        titleTransfer.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        titleTransfer.setForeground(new java.awt.Color(140, 118, 165));
        titleTransfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTransfer.setText("PLEASE ENTER BENEFICIARY ACCOUNT NUMBER:");

        accP1.setEditable(false);
        accP1.setBackground(new java.awt.Color(242, 187, 187));
        accP1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        accP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accP1.setBorder(null);
        accP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TRANSFERACCLayout = new javax.swing.GroupLayout(TRANSFERACC);
        TRANSFERACC.setLayout(TRANSFERACCLayout);
        TRANSFERACCLayout.setHorizontalGroup(
            TRANSFERACCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TRANSFERACCLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(titleTransfer)
                .addGap(19, 19, 19))
            .addGroup(TRANSFERACCLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(accP1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TRANSFERACCLayout.setVerticalGroup(
            TRANSFERACCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERACCLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(titleTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accP1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layeredPane.add(TRANSFERACC, "card7");

        AskReceipt.setBackground(new java.awt.Color(255, 239, 239));
        AskReceipt.setPreferredSize(new java.awt.Dimension(476, 256));

        NoReceipt.setBackground(new java.awt.Color(255, 239, 239));
        NoReceipt.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        NoReceipt.setForeground(new java.awt.Color(255, 102, 102));
        NoReceipt.setText(" NO");
        NoReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoReceiptActionPerformed(evt);
            }
        });

        Receipt.setBackground(new java.awt.Color(255, 239, 239));
        Receipt.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Receipt.setForeground(new java.awt.Color(0, 153, 153));
        Receipt.setText(" YES");
        Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 239, 239));
        jTextField2.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(140, 118, 165));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Do you want to print receipt?");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AskReceiptLayout = new javax.swing.GroupLayout(AskReceipt);
        AskReceipt.setLayout(AskReceiptLayout);
        AskReceiptLayout.setHorizontalGroup(
            AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AskReceiptLayout.createSequentialGroup()
                .addGroup(AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AskReceiptLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(NoReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AskReceiptLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        AskReceiptLayout.setVerticalGroup(
            AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AskReceiptLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoReceipt)
                    .addComponent(Receipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        layeredPane.add(AskReceipt, "card8");

        TRANSFERAMT.setBackground(new java.awt.Color(255, 239, 239));
        TRANSFERAMT.setPreferredSize(new java.awt.Dimension(476, 256));

        RM2.setEditable(false);
        RM2.setBackground(new java.awt.Color(255, 239, 239));
        RM2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RM2.setForeground(new java.awt.Color(140, 118, 165));
        RM2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM2.setText("RM");
        RM2.setBorder(null);
        RM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM2ActionPerformed(evt);
            }
        });

        amountTransfer.setEditable(false);
        amountTransfer.setBackground(new java.awt.Color(242, 187, 187));
        amountTransfer.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        amountTransfer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountTransfer.setBorder(null);
        amountTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTransferActionPerformed(evt);
            }
        });

        RM7.setEditable(false);
        RM7.setBackground(new java.awt.Color(255, 239, 239));
        RM7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RM7.setForeground(new java.awt.Color(140, 118, 165));
        RM7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RM7.setText(".00");
        RM7.setBorder(null);
        RM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM7ActionPerformed(evt);
            }
        });

        titleTransfer1.setBackground(new java.awt.Color(255, 239, 239));
        titleTransfer1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        titleTransfer1.setForeground(new java.awt.Color(140, 118, 165));
        titleTransfer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTransfer1.setText("PLEASE INSERT AMOUNT:");

        javax.swing.GroupLayout TRANSFERAMTLayout = new javax.swing.GroupLayout(TRANSFERAMT);
        TRANSFERAMT.setLayout(TRANSFERAMTLayout);
        TRANSFERAMTLayout.setHorizontalGroup(
            TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                .addGroup(TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(RM2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RM7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(titleTransfer1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        TRANSFERAMTLayout.setVerticalGroup(
            TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(titleTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        layeredPane.add(TRANSFERAMT, "card9");

        CONFIRMATION.setBackground(new java.awt.Color(255, 239, 239));
        CONFIRMATION.setPreferredSize(new java.awt.Dimension(476, 256));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 239, 239));
        jTextField5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(140, 118, 165));
        jTextField5.setText("Beneficiary Name:");
        jTextField5.setBorder(null);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 239, 239));
        jTextField6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(140, 118, 165));
        jTextField6.setText("Beneficiary Account Number:");
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 239, 239));
        jTextField7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(140, 118, 165));
        jTextField7.setText("Amount:");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        displayCardHolder.setEditable(false);
        displayCardHolder.setBackground(new java.awt.Color(255, 255, 255));
        displayCardHolder.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        displayCardHolder.setForeground(new java.awt.Color(113, 90, 138));
        displayCardHolder.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        displayCardHolder.setBorder(null);

        displayCardNo.setEditable(false);
        displayCardNo.setBackground(new java.awt.Color(255, 255, 255));
        displayCardNo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        displayCardNo.setForeground(new java.awt.Color(113, 90, 138));
        displayCardNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        displayCardNo.setBorder(null);

        displayTransferAmt.setEditable(false);
        displayTransferAmt.setBackground(new java.awt.Color(255, 255, 255));
        displayTransferAmt.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        displayTransferAmt.setForeground(new java.awt.Color(113, 90, 138));
        displayTransferAmt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        displayTransferAmt.setBorder(null);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 239, 239));
        jTextField11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(218, 138, 138));
        jTextField11.setText("Press ENTER to continue...");
        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONFIRMATIONLayout = new javax.swing.GroupLayout(CONFIRMATION);
        CONFIRMATION.setLayout(CONFIRMATIONLayout);
        CONFIRMATIONLayout.setHorizontalGroup(
            CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONFIRMATIONLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CONFIRMATIONLayout.createSequentialGroup()
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(136, 136, 136)
                            .addComponent(displayTransferAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(displayCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CONFIRMATIONLayout.createSequentialGroup()
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(displayCardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CONFIRMATIONLayout.setVerticalGroup(
            CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONFIRMATIONLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayCardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayTransferAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        layeredPane.add(CONFIRMATION, "card10");

        PROCESSING.setBackground(new java.awt.Color(255, 239, 239));
        PROCESSING.setForeground(new java.awt.Color(255, 239, 239));

        jTextField4.setBackground(new java.awt.Color(255, 239, 239));
        jTextField4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(140, 118, 165));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Are you confirm with your transaction?");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        RadioButton1.setBackground(new java.awt.Color(255, 239, 239));
        RadioButton1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RadioButton1.setForeground(new java.awt.Color(255, 102, 102));
        RadioButton1.setText("NO");
        RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton1ActionPerformed(evt);
            }
        });

        RadioButton2.setBackground(new java.awt.Color(255, 239, 239));
        RadioButton2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RadioButton2.setForeground(new java.awt.Color(71, 148, 148));
        RadioButton2.setText("YES");
        RadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PROCESSINGLayout = new javax.swing.GroupLayout(PROCESSING);
        PROCESSING.setLayout(PROCESSINGLayout);
        PROCESSINGLayout.setHorizontalGroup(
            PROCESSINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROCESSINGLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(RadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(PROCESSINGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PROCESSINGLayout.setVerticalGroup(
            PROCESSINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PROCESSINGLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PROCESSINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton1)
                    .addComponent(RadioButton2))
                .addGap(132, 132, 132))
        );

        layeredPane.add(PROCESSING, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layeredPane)
                    .addComponent(Keypad, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"1");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"1");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"1");    
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"1");
        }
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyActionPerformed
        
    }//GEN-LAST:event_btnEmptyActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"0");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"0");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"0");  
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"0");
        }
    }//GEN-LAST:event_btnZeroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void none(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_none
        
    }//GEN-LAST:event_none

    private void titleWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleWithdrawActionPerformed
       
    }//GEN-LAST:event_titleWithdrawActionPerformed

    private void RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMActionPerformed
       
    }//GEN-LAST:event_RMActionPerformed

    private void amountWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountWithdrawActionPerformed
       
    }//GEN-LAST:event_amountWithdrawActionPerformed

    private void titleDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleDepositActionPerformed
        
    }//GEN-LAST:event_titleDepositActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if(panel==0){
            JOptionPane.showMessageDialog(null, "End Session\n Thank you for visiting!");
            this.dispose();
            close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true);
        }
        else if(panel==1){         
            if(amountWithdraw.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                amountWithdraw.setText("");
            }
        }
        
        else if(panel==2){         
            if(amountDeposit.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                amountDeposit.setText("");
            }
        }
        
        else if(panel==3){
            if(accP1.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                accP1.setText("");
            }
        }
        
        else if(panel==3.1){
            if(amountTransfer.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                amountTransfer.setText("");
                accP1.setText("");
            }
        }
        else if(panel==3.2){
            switchPanels(MENU);
            panel=0;
            accP1.setText("");
            amountTransfer.setText("");
        }
        
      
        else if(panel==5){
                JOptionPane.showMessageDialog(null, "End Session\n Thank you for visiting!");
                this.dispose();
            close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true);
            }
        else{
            switchPanels(MENU);
            panel=0;
        }
          
        
       
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"2");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"2");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"2");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"2");
        }
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
       if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"3");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"3");
        }
       else if(panel==3){
                accP1.setText(accP1.getText()+"3");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"3");
        }
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"4");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"4");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"4");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"4");
        }
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"5");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"5");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"5");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"5");
        }
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
       if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"6");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"6");
        }
       else if(panel==3){
                accP1.setText(accP1.getText()+"6");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"6");
        }
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
       if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"7");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"7");
        }
       else if(panel==3){
                accP1.setText(accP1.getText()+"7");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"7");
        }
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"8");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"8");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"8");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"8");
        }
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"9");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"9");
        }
        else if(panel==3){
                accP1.setText(accP1.getText()+"9");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"9");
        }
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnDoubleZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleZeroActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"00");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"00");
        }
        else if(panel==3){
               accP1.setText(accP1.getText()+"00");
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"00");
        }
    }//GEN-LAST:event_btnDoubleZeroActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         String backspace = null;
        if(panel==1){         
            if(amountWithdraw.getText().length() > 0){
                StringBuilder strB = new StringBuilder(amountWithdraw.getText());
                strB.deleteCharAt(amountWithdraw.getText().length()-1);
                backspace = strB.toString();
                amountWithdraw.setText(backspace);
            }
        }
        else if(panel==2){
            if(amountDeposit.getText().length() > 0){
                StringBuilder strB = new StringBuilder(amountDeposit.getText());
                strB.deleteCharAt(amountDeposit.getText().length()-1);
                backspace = strB.toString();
                amountDeposit.setText(backspace);
            }
        }
        else if(panel==3){
                        if(accP1.getText().length() > 0){
                            StringBuilder strB = new StringBuilder(accP1.getText());
                            strB.deleteCharAt(accP1.getText().length()-1);
                            backspace = strB.toString();
                            accP1.setText(backspace);
                        }
        }
        else if(panel==3.1){
            if(amountTransfer.getText().length() > 0){
                StringBuilder strB = new StringBuilder(amountTransfer.getText());
                strB.deleteCharAt(amountTransfer.getText().length()-1);
                backspace = strB.toString();
                amountTransfer.setText(backspace);
            }
            
        }
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void showAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAccNoActionPerformed
        //Display user AccNo      
    }//GEN-LAST:event_showAccNoActionPerformed

    private void showBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBalanceActionPerformed
        // Display user balance
        
    }//GEN-LAST:event_showBalanceActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        //WITHDRAW PAGE
        if(panel==1){ 
            Boolean agree=true;
            double amtWithdraw = tranc.StringToDouble(amountWithdraw.getText());
            
            if(amtWithdraw>5000){
                agree = false;
                JOptionPane.showMessageDialog(null, "The maximum of withrawal is RM5000!");
                amountWithdraw.setText("");                
            }
            
            if(amtWithdraw>=current_user.returnBalance()-20){
                agree = false;
                JOptionPane.showMessageDialog(null, "Insufficient funds in your account!");
                amountWithdraw.setText("");                
            }
            
            //System.out.print(amtWithdraw);
          // switchPanels(DEPOSIT2);
          //  panel = 1.1;
          if(agree==true){
              Withdraw w = new Withdraw(current_user.returnAcc(),amtWithdraw);
              transac_id = w.returnID();   
              transac_date = w.returnDate();
              transac_amount = amtWithdraw;
            JOptionPane.showMessageDialog(frame, df.format(amtWithdraw) +
                                " withdrawn from your account.");
            panel = 5;
            transac_type = 1;
            switchPanels(AskReceipt);
          }
            
        }
        
         //DEPOSIT PAGE
        else if(panel==2){
            Deposit d= new Deposit(current_user.returnAcc(),tranc.StringToDouble(amountDeposit.getText()));
            transac_amount = tranc.StringToDouble(amountDeposit.getText());
            transac_id = d.returnID();
            transac_date = d.returnDate();
            JOptionPane.showMessageDialog(frame, df.format(tranc.StringToDouble(amountDeposit.getText())) +
                                " deposited into your account.");
            
            //Progress bar
            panel =5;
            transac_type = 2;
            switchPanels(AskReceipt);            
        }
        
         //TRANSFER PAGE
        else if(panel==3){
            String acc_no = accP1.getText();
            int match = 0;
            //System.out.println(totalUser+" in GUI");
            if(acc_no.length()== 8){
                for(int i = 0;i<totalUser;i++){
                    System.out.println(user_card[i].returnAccNo()+" in loop");
                    if(acc_no.equals(user_card[i].returnAccNo())){
                        System.out.println(user_card[i].returnAccNo()+"in if");
                        recipient = user_card[i];
                        match = 1;
                        break;
                    }
                }
            }
            
            if(acc_no.equals(current_user.returnAccNo())){
                JOptionPane.showMessageDialog(null, "Please choose DEPOSIT to continue your transaction!\nPlease try again.");
                accP1.setText("");
                switchPanels(MENU);
                panel=0;
            }
            else if(match == 0){
                JOptionPane.showMessageDialog(null, "Invalid account number!\nPlease try again.");
                accP1.setText("");
            }
            else{
                switchPanels(TRANSFERAMT);
                panel =3.1;
            }
      //here check the existence of account
            /*if(success){
                displayCardNo.setText(card_no);
                switchPanels(TRANSFERAMT);
                panel = 3.1;
                
           /* }
            else{
             JOptionPane.showMessageDialog(null, "This account does not exist!\nPlease try again.");
                transferAcc.setText("");            
            }
            */
        }
        
        //ENTER TRANSFER AMOUNT
        else if(panel==3.1){
            Boolean agree=true;
            amtTransfer = tranc.StringToDouble(amountTransfer.getText());
            if(amtTransfer>5000){
                agree = false;
                JOptionPane.showMessageDialog(null, "The maximum for tranfer amount is RM5000!");
                amountTransfer.setText("");                
            }
            if(amtTransfer>(current_user.returnBalance()-20)){
                agree = false;
                JOptionPane.showMessageDialog(null, "Insufficient funds in your account!Please try again.");
                amountTransfer.setText("");                
            }
          if(agree==true){
              switchPanels(PROCESSING);
              panel = 3.3;
              
          }
       
        }
        
      /*  else if(panel==3.3)
        {
            
        }*/
        
        else if(panel==3.2){
            panel = 5;
            switchPanels(AskReceipt); 
        }    
         //BALANCE PAGE
        else if(panel==4){
            panel = 5;
            switchPanels(AskReceipt);
        }
        else if(panel==5){
            generateReceipt(current_user,transac_type);
            updatetxt();
            JOptionPane.showMessageDialog(null, "Kindly check your receipt.\n Thank you for visiting!");
            this.dispose();
            close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true); 
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void amountDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountDepositActionPerformed

    private void RM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM1ActionPerformed

    private void RM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM5ActionPerformed

    private void RM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM6ActionPerformed

    private void ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptActionPerformed
        //Print Receipt here
        generateReceipt(current_user,transac_type);
        updatetxt();
        JOptionPane.showMessageDialog(null, "Kindly check your receipt.\n Thank you for visiting!");
        this.dispose();
        close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true); 
    }//GEN-LAST:event_ReceiptActionPerformed

    private void NoReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoReceiptActionPerformed
        //Thanks for visiting....
        updatetxt();
        JOptionPane.showMessageDialog(null, "End Session\n Thank you for visiting!");
        this.dispose();
        close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true);
    }//GEN-LAST:event_NoReceiptActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void RM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM2ActionPerformed

    private void amountTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTransferActionPerformed

    private void RM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM7ActionPerformed

    private void accP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accP1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton1ActionPerformed
        
         switchPanels(TRANSFERAMT);
         panel=3.1;
         amountTransfer.setText("");
         RadioButton1.setSelected(false);
    }//GEN-LAST:event_RadioButton1ActionPerformed

    private void RadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton2ActionPerformed
        // TODO add your handling code here:
         //do transfer here
              Transfer tr =new Transfer(current_user.returnAcc(),amtTransfer,recipient);
              transac_amount = amtTransfer;
              transac_id = tr.returnID();
              transac_date = tr.returnDate();
              recipient_name = tr.returnReceiptName();
              tr.getSummaryLine();
              displayCardNo.setText(recipient.returnAccNo());
              displayCardHolder.setText(recipient.returnAcc().getAccHolder());
              //displayTransferAmt.setText(df.format(recipient.returnBalance()));
              displayTransferAmt.setText(df.format(amtTransfer));
              
              transac_type = 3;
              switchPanels(CONFIRMATION);
              panel = 3.2;
              RadioButton2.setSelected(false);
    }//GEN-LAST:event_RadioButton2ActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        switchPanels(TRANSFERACC);
        panel=3;
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        switchPanels(DEPOSIT1);
        panel=2;
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        switchPanels(WITHDRAW);
        panel=1;

    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        switchPanels(BALANCE);
        showAccNo.setText(current_user.getCardNo());
        balance = current_user.returnBalance();
        String str = String.format("%.2f",balance);
        showBalance.setText(str);
        panel=4;
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    public static void generateReceipt(user user_card, int transactionType){ 
        Account acct = user_card.returnAcc();
        Double availableBalance = acct.getBalance();
        String acc_no = acct.getAccNo();
        String avaBalance = String.format("%.2f",availableBalance);
        String trans_amt = String.format("%.2f",transac_amount);
        String type="";
        String lastDigit = user_card.getCardNo();
        lastDigit = lastDigit.substring(14);

        if(transactionType==1)
        {
            type = "WITHDRAWAL";
        }
        else if(transactionType==2)
        {
            type = "DEPOSIT";
        }
        else if(transactionType==3)
        {
            type = "TRANSFER";
        }
        else if(transactionType==4)
        {
            type = "BALANCE ENQUIRY";
        }

        String receiptName = "Receipt_"+transac_id+".txt";
        File receipt = new File(receiptName);

        try {
            FileReader read = new FileReader(receipt);
            System.out.println("File exists!");
        } catch (FileNotFoundException ex) {
            try {
                FileWriter write = new FileWriter(receipt);
                System.out.println("File created!");
            } catch (IOException ex1) {
               System.out.println("Failed to create file!");
            }
        }
        
        try {
            System.out.println("Printing receipt...");
            RandomAccessFile write = new RandomAccessFile(receipt, "rw");
            write.writeBytes("***************************************\n");
            write.writeBytes("       Unicorn Bank ATM's receipt\n");
            write.writeBytes("***************************************\n");
            write.writeBytes("  Date:"+transac_date.substring(0,11)+"\n");
            write.writeBytes("  Time:"+transac_date.substring(11)+"\n");
            write.writeBytes("\n");
            write.writeBytes("  Card Number\n");
            write.writeBytes("  xxxx-xxxx-xxxx"+lastDigit+"\n");
            write.writeBytes("\n");
            if(type == "TRANSFER")
            {
                write.writeBytes("  TRANSACTION #"+transac_id+"\n");
                write.writeBytes("  TRANSFER MONEY\n");
                write.writeBytes("  TO A/C Holder: "+recipient_name+"\n");
                write.writeBytes("  AMOUNT: RM "+trans_amt+"\n");
                write.writeBytes("  FROM ACC NO: "+acc_no+"\n");
            }
            else if(type == "DEPOSIT")
            {
                write.writeBytes("  TRANSACTION #"+transac_id+"\n");
                write.writeBytes("  DEPOSIT\n");
                write.writeBytes("  CASH: RM "+trans_amt+"\n");
                write.writeBytes("  IN ACC NO: "+acc_no+"\n");
            }
            else if(type == "WITHDRAWAL")
            {
                write.writeBytes("  TRANSACTION #"+transac_id+"\n");
                write.writeBytes("  WITHDRAWAL\n");  
                write.writeBytes("  CASH: RM "+trans_amt+"\n");
                write.writeBytes("  FROM ACC NO: "+acc_no+"\n");
            }
            else
            {
                write.writeBytes("  BALANCE ENQUIRY\n");    
                write.writeBytes("  IN ACC NO: "+acc_no+"\n");
            }
            write.writeBytes("  Available balance: RM"+avaBalance+"\n");
            write.writeBytes("\n");
            write.writeBytes("\n");
            write.writeBytes(" Thank you for using Unicorn Bank ATM!\n");
            write.writeBytes("***************************************\n");
        }
        catch (IOException ex) {
            System.out.println("File not found!");
        }
        
    }
    
    public void updatetxt()
    {
        try 
        {
            File file = new File("user.txt");
            try (FileWriter overwrite = new FileWriter(file,false)) {
                System.out.println("Overwriting user.txt...");
                for(int i=0;i<totalUser;i++)
                {
                    String cardNo = user_card[i].getCardNo();
                    String password = user_card[i].getPinNo();
                    String accHolder = user_card[i].returnAccHolder();
                    String accNo = user_card[i].returnAccNo();
                    Double bal = user_card[i].returnBalance();
                    overwrite.write("Card Num:"+cardNo+"\n");
                    overwrite.write("Pin Num:"+password+"\n");
                    overwrite.write("Acc Holder:"+accHolder+"\n");
                    overwrite.write("Acc Num:"+accNo+"\n");
                    overwrite.write("Balance:");
                    overwrite.write(String.format("%.2f", bal)+"\n");
                    overwrite.write("\n");
                }
                overwrite.close();
            }
               
        }
        catch (FileNotFoundException ex) {
          	System.out.println("File not found in your device!");
        } catch (IOException ex) {
         	System.out.println("Failed to read the file!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
      
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AskReceipt;
    private javax.swing.JPanel BALANCE;
    private javax.swing.JPanel CONFIRMATION;
    private javax.swing.JPanel DEPOSIT1;
    private javax.swing.JPanel Keypad;
    private javax.swing.JPanel MENU;
    private javax.swing.JRadioButton NoReceipt;
    private javax.swing.JPanel PROCESSING;
    private javax.swing.JTextField RM;
    private javax.swing.JTextField RM1;
    private javax.swing.JTextField RM2;
    private javax.swing.JTextField RM5;
    private javax.swing.JTextField RM6;
    private javax.swing.JTextField RM7;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JRadioButton Receipt;
    private javax.swing.JPanel TRANSFERACC;
    private javax.swing.JPanel TRANSFERAMT;
    private javax.swing.JPanel WITHDRAW;
    private javax.swing.JTextField accP1;
    private javax.swing.JTextField amountDeposit;
    private javax.swing.JTextField amountTransfer;
    private javax.swing.JTextField amountWithdraw;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnDoubleZero;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEmpty;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnZero;
    private javax.swing.JTextField displayCardHolder;
    private javax.swing.JTextField displayCardNo;
    private javax.swing.JTextField displayTransferAmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JTextField showAccNo;
    private javax.swing.JTextField showBalance;
    private javax.swing.JTextField titleDeposit;
    private javax.swing.JLabel titleTransfer;
    private javax.swing.JLabel titleTransfer1;
    private javax.swing.JTextField titleWithdraw;
    // End of variables declaration//GEN-END:variables
}
