/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Scanner;
import javax.swing.ImageIcon;
import java.awt.event.*;
import java.awt.*;
/**
 *
 * @author User
 */
public class GUI_old extends javax.swing.JFrame {
    
    static user[] user_card;
    static int totalUser;
    static int userNo;
    static double panel = 0; 
    static user current_user;
    static user recipient;
    static double balance;
    static Transaction tranc = new Transaction();
    static DecimalFormat df = new DecimalFormat("$0.00");
    static JOptionPane frame = new JOptionPane();
/* 0 = MENU; 1=WITHDRAW; 2=DEPOSIT; 3=TRANSFER; 4=BALANCE; 5=RECEIPT*/
/* 1.1 WITHDRAW PROGRESS */
    
    private Timer t;
    private ActionListener al;
    
    
    
    /**
     * Creates new form GUI
     */
    public GUI_old() {
        initComponents();
    }
    
    public GUI_old(user[]user_card,int userNo,int totalUser){
        this.totalUser=totalUser;
        this.user_card = user_card;
        current_user= user_card[userNo];
        initComponents(); 
        
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public void switchPanels(JPanel pane){
        layeredPane.removeAll();
        layeredPane.add(pane);
        layeredPane.repaint();
        layeredPane.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Keypad = new javax.swing.JPanel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnEmpty = new javax.swing.JButton();
        btnDoubleZero = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        layeredPane = new javax.swing.JLayeredPane();
        MENU = new javax.swing.JPanel();
        btnBalance = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        WITHDRAW = new javax.swing.JPanel();
        titleWithdraw = new javax.swing.JTextField();
        RM = new javax.swing.JTextField();
        amountWithdraw = new javax.swing.JTextField();
        RM6 = new javax.swing.JTextField();
        DEPOSIT1 = new javax.swing.JPanel();
        titleDeposit = new javax.swing.JTextField();
        RM1 = new javax.swing.JTextField();
        amountDeposit = new javax.swing.JTextField();
        RM5 = new javax.swing.JTextField();
        BALANCE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showAccNo = new javax.swing.JTextField();
        showBalance = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        TRANSFERACC = new javax.swing.JPanel();
        titleTransfer = new javax.swing.JLabel();
        accP1 = new javax.swing.JTextField();
        accP2 = new javax.swing.JTextField();
        accP4 = new javax.swing.JTextField();
        accP3 = new javax.swing.JTextField();
        AskReceipt = new javax.swing.JPanel();
        NoReceipt = new javax.swing.JRadioButton();
        Receipt = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        TRANSFERAMT = new javax.swing.JPanel();
        RM2 = new javax.swing.JTextField();
        amountTransfer = new javax.swing.JTextField();
        RM7 = new javax.swing.JTextField();
        titleTransfer1 = new javax.swing.JLabel();
        CONFIRMATION = new javax.swing.JPanel();
        TRANSFERAMT1 = new javax.swing.JPanel();
        RM3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        displayCardHolder = new javax.swing.JTextField();
        displayCardNo = new javax.swing.JTextField();
        displayTransferAmt = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu\n");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
                none(evt);
            }
        });

        Keypad.setBackground(new java.awt.Color(102, 102, 102));
        Keypad.setPreferredSize(new java.awt.Dimension(360, 360));

        btnOne.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 51, 0));
        btnCancel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 0));
        btnClear.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorderPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyActionPerformed(evt);
            }
        });

        btnDoubleZero.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnDoubleZero.setText("00");
        btnDoubleZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleZeroActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(0, 255, 51));
        btnEnter.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnEnter.setText("ENTER");
        btnEnter.setBorderPainted(false);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnDecimal.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnDecimal.setText(".");

        javax.swing.GroupLayout KeypadLayout = new javax.swing.GroupLayout(Keypad);
        Keypad.setLayout(KeypadLayout);
        KeypadLayout.setHorizontalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSeven, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDoubleZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        KeypadLayout.setVerticalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoubleZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );

        layeredPane.setOpaque(true);
        layeredPane.setPreferredSize(new java.awt.Dimension(360, 360));
        layeredPane.setLayout(new java.awt.CardLayout());

        MENU.setBackground(new java.awt.Color(204, 255, 204));
        MENU.setPreferredSize(new java.awt.Dimension(442, 256));

        btnBalance.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnBalance.setText("BALANCE");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnWithdraw.setText("WITHDRAW");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnDeposit.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnDeposit.setText("DEPOSIT");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnTransfer.setText("TRANSFER");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU);
        MENU.setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENULayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        layeredPane.add(MENU, "card2");

        WITHDRAW.setBackground(new java.awt.Color(204, 255, 204));
        WITHDRAW.setPreferredSize(new java.awt.Dimension(442, 256));

        titleWithdraw.setEditable(false);
        titleWithdraw.setBackground(new java.awt.Color(204, 255, 204));
        titleWithdraw.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        titleWithdraw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleWithdraw.setText("Please Enter Amount:");
        titleWithdraw.setBorder(null);
        titleWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleWithdrawActionPerformed(evt);
            }
        });

        RM.setEditable(false);
        RM.setBackground(new java.awt.Color(204, 255, 204));
        RM.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM.setText("RM");
        RM.setBorder(null);
        RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMActionPerformed(evt);
            }
        });

        amountWithdraw.setEditable(false);
        amountWithdraw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountWithdraw.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountWithdraw.setBorder(null);
        amountWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountWithdrawActionPerformed(evt);
            }
        });

        RM6.setEditable(false);
        RM6.setBackground(new java.awt.Color(204, 255, 204));
        RM6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RM6.setText(".00");
        RM6.setBorder(null);
        RM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WITHDRAWLayout = new javax.swing.GroupLayout(WITHDRAW);
        WITHDRAW.setLayout(WITHDRAWLayout);
        WITHDRAWLayout.setHorizontalGroup(
            WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WITHDRAWLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(WITHDRAWLayout.createSequentialGroup()
                        .addComponent(RM, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RM6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        WITHDRAWLayout.setVerticalGroup(
            WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WITHDRAWLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titleWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WITHDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        layeredPane.add(WITHDRAW, "card3");

        DEPOSIT1.setBackground(new java.awt.Color(204, 255, 204));
        DEPOSIT1.setPreferredSize(new java.awt.Dimension(442, 256));

        titleDeposit.setEditable(false);
        titleDeposit.setBackground(new java.awt.Color(204, 255, 204));
        titleDeposit.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        titleDeposit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleDeposit.setText("Please Enter Amount:");
        titleDeposit.setBorder(null);
        titleDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleDepositActionPerformed(evt);
            }
        });

        RM1.setEditable(false);
        RM1.setBackground(new java.awt.Color(204, 255, 204));
        RM1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM1.setText("RM");
        RM1.setBorder(null);
        RM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM1ActionPerformed(evt);
            }
        });

        amountDeposit.setEditable(false);
        amountDeposit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountDeposit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountDeposit.setBorder(null);
        amountDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountDepositActionPerformed(evt);
            }
        });

        RM5.setEditable(false);
        RM5.setBackground(new java.awt.Color(204, 255, 204));
        RM5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RM5.setText(".00");
        RM5.setBorder(null);
        RM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DEPOSIT1Layout = new javax.swing.GroupLayout(DEPOSIT1);
        DEPOSIT1.setLayout(DEPOSIT1Layout);
        DEPOSIT1Layout.setHorizontalGroup(
            DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSIT1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DEPOSIT1Layout.createSequentialGroup()
                        .addComponent(RM1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RM5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        DEPOSIT1Layout.setVerticalGroup(
            DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSIT1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(titleDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DEPOSIT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        layeredPane.add(DEPOSIT1, "card4");

        BALANCE.setBackground(new java.awt.Color(204, 255, 204));
        BALANCE.setPreferredSize(new java.awt.Dimension(442, 256));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setText("Balance     :");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setText("Card No.    : ");

        showAccNo.setEditable(false);
        showAccNo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        showAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAccNoActionPerformed(evt);
            }
        });

        showBalance.setEditable(false);
        showBalance.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        showBalance.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        showBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBalanceActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("RM");

        javax.swing.GroupLayout BALANCELayout = new javax.swing.GroupLayout(BALANCE);
        BALANCE.setLayout(BALANCELayout);
        BALANCELayout.setHorizontalGroup(
            BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BALANCELayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BALANCELayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showBalance))
                    .addComponent(showAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BALANCELayout.setVerticalGroup(
            BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BALANCELayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(BALANCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        layeredPane.add(BALANCE, "card6");

        TRANSFERACC.setBackground(new java.awt.Color(204, 255, 204));
        TRANSFERACC.setPreferredSize(new java.awt.Dimension(442, 256));

        titleTransfer.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        titleTransfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTransfer.setText("PLEASE ENTER BENEFICIARY CARD NUMBER:");

        accP1.setEditable(false);
        accP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accP1ActionPerformed(evt);
            }
        });

        accP2.setEditable(false);
        accP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accP2ActionPerformed(evt);
            }
        });

        accP4.setEditable(false);
        accP4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accP4ActionPerformed(evt);
            }
        });

        accP3.setEditable(false);
        accP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TRANSFERACCLayout = new javax.swing.GroupLayout(TRANSFERACC);
        TRANSFERACC.setLayout(TRANSFERACCLayout);
        TRANSFERACCLayout.setHorizontalGroup(
            TRANSFERACCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERACCLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(accP1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accP2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accP3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accP4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(TRANSFERACCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TRANSFERACCLayout.setVerticalGroup(
            TRANSFERACCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERACCLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(titleTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TRANSFERACCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accP1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accP2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accP3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accP4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layeredPane.add(TRANSFERACC, "card7");

        AskReceipt.setBackground(new java.awt.Color(204, 255, 204));
        AskReceipt.setPreferredSize(new java.awt.Dimension(442, 256));

        NoReceipt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        NoReceipt.setText("NO");
        NoReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoReceiptActionPerformed(evt);
            }
        });

        Receipt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Receipt.setText("YES");
        Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 255, 204));
        jTextField2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Do you want to print receipt?");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AskReceiptLayout = new javax.swing.GroupLayout(AskReceipt);
        AskReceipt.setLayout(AskReceiptLayout);
        AskReceiptLayout.setHorizontalGroup(
            AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AskReceiptLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AskReceiptLayout.createSequentialGroup()
                        .addComponent(NoReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Receipt))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AskReceiptLayout.setVerticalGroup(
            AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AskReceiptLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(AskReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoReceipt)
                    .addComponent(Receipt))
                .addGap(50, 50, 50))
        );

        layeredPane.add(AskReceipt, "card8");

        TRANSFERAMT.setBackground(new java.awt.Color(204, 255, 204));
        TRANSFERAMT.setPreferredSize(new java.awt.Dimension(442, 256));

        RM2.setEditable(false);
        RM2.setBackground(new java.awt.Color(204, 255, 204));
        RM2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM2.setText("RM");
        RM2.setBorder(null);
        RM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM2ActionPerformed(evt);
            }
        });

        amountTransfer.setEditable(false);
        amountTransfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountTransfer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountTransfer.setBorder(null);
        amountTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTransferActionPerformed(evt);
            }
        });

        RM7.setEditable(false);
        RM7.setBackground(new java.awt.Color(204, 255, 204));
        RM7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RM7.setText(".00");
        RM7.setBorder(null);
        RM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM7ActionPerformed(evt);
            }
        });

        titleTransfer1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        titleTransfer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTransfer1.setText("PLEASE ENTER AMOUNT:");

        javax.swing.GroupLayout TRANSFERAMTLayout = new javax.swing.GroupLayout(TRANSFERAMT);
        TRANSFERAMT.setLayout(TRANSFERAMTLayout);
        TRANSFERAMTLayout.setHorizontalGroup(
            TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                        .addComponent(RM2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RM7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        TRANSFERAMTLayout.setVerticalGroup(
            TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERAMTLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(titleTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TRANSFERAMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        layeredPane.add(TRANSFERAMT, "card9");

        TRANSFERAMT1.setBackground(new java.awt.Color(204, 255, 204));
        TRANSFERAMT1.setPreferredSize(new java.awt.Dimension(442, 256));

        RM3.setEditable(false);
        RM3.setBackground(new java.awt.Color(204, 255, 204));
        RM3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RM3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RM3.setText("RM");
        RM3.setBorder(null);
        RM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM3ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 255, 204));
        jTextField5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextField5.setText("Beneficiary Name:");
        jTextField5.setBorder(null);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 255, 204));
        jTextField6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextField6.setText("Card Number:");
        jTextField6.setBorder(null);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 255, 204));
        jTextField7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextField7.setText("Amount:");
        jTextField7.setBorder(null);

        displayCardHolder.setEditable(false);
        displayCardHolder.setBackground(new java.awt.Color(255, 255, 255));
        displayCardHolder.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        displayCardHolder.setBorder(null);
        displayCardHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCardHolderActionPerformed(evt);
            }
        });

        displayCardNo.setEditable(false);
        displayCardNo.setBackground(new java.awt.Color(255, 255, 255));
        displayCardNo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        displayCardNo.setBorder(null);
        displayCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCardNoActionPerformed(evt);
            }
        });

        displayTransferAmt.setEditable(false);
        displayTransferAmt.setBackground(new java.awt.Color(255, 255, 255));
        displayTransferAmt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        displayTransferAmt.setBorder(null);
        displayTransferAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTransferAmtActionPerformed(evt);
            }
        });

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(204, 255, 204));
        jTextField11.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextField11.setText("Press ENTER to continue...");
        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TRANSFERAMT1Layout = new javax.swing.GroupLayout(TRANSFERAMT1);
        TRANSFERAMT1.setLayout(TRANSFERAMT1Layout);
        TRANSFERAMT1Layout.setHorizontalGroup(
            TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERAMT1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TRANSFERAMT1Layout.createSequentialGroup()
                        .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5))
                        .addGap(18, 18, 18)
                        .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayCardNo)
                            .addComponent(displayCardHolder)
                            .addComponent(displayTransferAmt))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TRANSFERAMT1Layout.createSequentialGroup()
                        .addGap(0, 219, Short.MAX_VALUE)
                        .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TRANSFERAMT1Layout.createSequentialGroup()
                                .addComponent(RM3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TRANSFERAMT1Layout.createSequentialGroup()
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        TRANSFERAMT1Layout.setVerticalGroup(
            TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANSFERAMT1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayCardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(TRANSFERAMT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayTransferAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(RM3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CONFIRMATIONLayout = new javax.swing.GroupLayout(CONFIRMATION);
        CONFIRMATION.setLayout(CONFIRMATIONLayout);
        CONFIRMATIONLayout.setHorizontalGroup(
            CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CONFIRMATIONLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TRANSFERAMT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CONFIRMATIONLayout.setVerticalGroup(
            CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
            .addGroup(CONFIRMATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CONFIRMATIONLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TRANSFERAMT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        layeredPane.add(CONFIRMATION, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"1");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"1");
        }
        else if(panel==3){
            if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"1");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"1");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"1");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"1");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"1");
        }
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyActionPerformed
        
    }//GEN-LAST:event_btnEmptyActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"0");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"0");
        }
        else if(panel==3){
           if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"0");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"0");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"0");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"0");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"0");
        }
    }//GEN-LAST:event_btnZeroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void none(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_none
        
    }//GEN-LAST:event_none

    private void titleWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleWithdrawActionPerformed
       
    }//GEN-LAST:event_titleWithdrawActionPerformed

    private void RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMActionPerformed
       
    }//GEN-LAST:event_RMActionPerformed

    private void amountWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountWithdrawActionPerformed
       
    }//GEN-LAST:event_amountWithdrawActionPerformed

    private void titleDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleDepositActionPerformed
        
    }//GEN-LAST:event_titleDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
       switchPanels(WITHDRAW);
        panel=1;
        
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        switchPanels(DEPOSIT1);
        panel=2;
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
       switchPanels(TRANSFERACC);
        panel=3;
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        switchPanels(BALANCE);
        showAccNo.setText(current_user.getCardNo());
        balance = current_user.returnBalance();
        String str = String.format("%.2f",balance);
        showBalance.setText(str);
        panel=4;
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if(panel==0){
            JOptionPane.showMessageDialog(null, "End Session\n Thank you for visiting!");
            this.dispose();
            close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true);
        }
        else if(panel==1){         
            if(amountWithdraw.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                amountWithdraw.setText("");
            }
        }
        
        else if(panel==2){         
            if(amountDeposit.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                amountDeposit.setText("");
            }
        }
        
        else if(panel==3){
            if(accP1.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                accP4.setText("");
                accP3.setText("");
                accP2.setText("");
                accP1.setText("");
            }
        }
        
        else if(panel==3.1){
            if(amountTransfer.getText().length() == 0){
                 switchPanels(MENU);
                 panel=0;
            }
            else{
                amountTransfer.setText("");
            }
        }
        else if(panel==5){
                JOptionPane.showMessageDialog(null, "End Session\n Thank you for visiting!");
                this.dispose();
            close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true);
            }
        else{
            switchPanels(MENU);
            panel=0;
        }
          
        
       
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"2");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"2");
        }
        else if(panel==3){
           if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"2");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"2");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"2");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"2");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"2");
        }
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
       if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"3");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"3");
        }
       else if(panel==3){
            if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"3");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"3");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"3");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"3");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"3");
        }
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"4");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"4");
        }
        else if(panel==3){
             if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"4");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"4");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"4");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"4");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"4");
        }
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"5");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"5");
        }
        else if(panel==3){
            if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"5");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"5");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"5");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"5");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"5");
        }
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
       if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"6");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"6");
        }
       else if(panel==3){
             if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"6");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"6");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"6");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"6");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"6");
        }
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
       if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"7");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"7");
        }
       else if(panel==3){
            if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"7");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"7");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"7");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"7");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"7");
        }
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"8");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"8");
        }
        else if(panel==3){
             if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"8");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"8");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"8");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"8");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"8");
        }
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"9");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"9");
        }
        else if(panel==3){
            if(accP1.getText().length()<4){
                accP1.setText(accP1.getText()+"9");
            }            
            else if(accP1.getText().length()==4){
                if(accP2.getText().length()<4){
                    accP2.setText(accP2.getText()+"9");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<4){
                        accP3.setText(accP3.getText()+"9");
                    }
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<4){
                            accP4.setText(accP4.getText()+"9");
                        }
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"9");
        }
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnDoubleZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleZeroActionPerformed
        if(panel==1){
            amountWithdraw.setText(amountWithdraw.getText()+"00");
        }
        else if(panel==2){
            amountDeposit.setText(amountDeposit.getText()+"00");
        }
        else if(panel==3){
             if(accP1.getText().length()<=2 && accP1.getText().length()>=1){
                accP1.setText(accP1.getText()+"00");
            }
             else if(accP1.getText().length()==3){
                 accP1.setText(accP1.getText()+"0");
                 accP2.setText(accP2.getText()+"0");
             }
             else if(accP1.getText().length()==4){
                if(accP2.getText().length()<=2 && accP2.getText().length()>=1){
                    accP2.setText(accP2.getText()+"00");
                }
                else if(accP2.getText().length()==3){
                 accP2.setText(accP2.getText()+"0");
                 accP3.setText(accP3.getText()+"0");
                }
                else if(accP2.getText().length()==4){
                    if(accP3.getText().length()<=2 && accP3.getText().length()>=1){
                        accP3.setText(accP3.getText()+"00");
                    }
                    else if(accP3.getText().length()==3){
                     accP3.setText(accP3.getText()+"0");
                     accP4.setText(accP4.getText()+"0");
                    }
                   
                    else if(accP3.getText().length()==4){
                        if(accP4.getText().length()<=2 && accP4.getText().length()>=1){
                            accP4.setText(accP4.getText()+"00");
                        }
                        
                    }
                }
            }
        }
        else if(panel==3.1){
            amountTransfer.setText(amountTransfer.getText()+"00");
        }
    }//GEN-LAST:event_btnDoubleZeroActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         String backspace = null;
        if(panel==1){         
            if(amountWithdraw.getText().length() > 0){
                StringBuilder strB = new StringBuilder(amountWithdraw.getText());
                strB.deleteCharAt(amountWithdraw.getText().length()-1);
                backspace = strB.toString();
                amountWithdraw.setText(backspace);
            }
        }
        else if(panel==2){
            if(amountDeposit.getText().length() > 0){
                StringBuilder strB = new StringBuilder(amountDeposit.getText());
                strB.deleteCharAt(amountDeposit.getText().length()-1);
                backspace = strB.toString();
                amountDeposit.setText(backspace);
            }
        }
        else if(panel==3){
            if(accP4.getText().length() > 0){
                StringBuilder strB = new StringBuilder(accP4.getText());
                strB.deleteCharAt(accP4.getText().length()-1);
                backspace = strB.toString();
                accP4.setText(backspace);
            }
            else{
                if(accP4.getText().length()==0 && accP3.getText().length() > 0){
                    StringBuilder strB = new StringBuilder(accP3.getText());
                    strB.deleteCharAt(accP3.getText().length()-1);
                    backspace = strB.toString();
                    accP3.setText(backspace);
                }
                else{
                    if(accP3.getText().length()==0 && accP2.getText().length() > 0){
                        StringBuilder strB = new StringBuilder(accP2.getText());
                        strB.deleteCharAt(accP2.getText().length()-1);
                        backspace = strB.toString();
                        accP2.setText(backspace);
                    }
                    else{
                        if(accP2.getText().length()==0 && accP1.getText().length() > 0){
                            StringBuilder strB = new StringBuilder(accP1.getText());
                            strB.deleteCharAt(accP1.getText().length()-1);
                            backspace = strB.toString();
                            accP1.setText(backspace);
                        }
                }
                }
            }
        }
        else if(panel==3.1){
            if(amountTransfer.getText().length() > 0){
                StringBuilder strB = new StringBuilder(amountTransfer.getText());
                strB.deleteCharAt(amountTransfer.getText().length()-1);
                backspace = strB.toString();
                amountTransfer.setText(backspace);
            }
            
        }
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void showAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAccNoActionPerformed
        //Display user AccNo      
    }//GEN-LAST:event_showAccNoActionPerformed

    private void showBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBalanceActionPerformed
        // Display user balance
        
    }//GEN-LAST:event_showBalanceActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        //WITHDRAW PAGE
        if(panel==1){ 
            Boolean agree=true;
            double amtWithdraw = tranc.StringToDouble(amountWithdraw.getText());
            
            if(amtWithdraw>5000){
                agree = false;
                JOptionPane.showMessageDialog(null, "The maximum of withrawal is RM5000!");
                amountWithdraw.setText("");                
            }
            
            if(amtWithdraw>=current_user.returnBalance()-20){
                agree = false;
                JOptionPane.showMessageDialog(null, "Insufficient funds in your account!");
                amountWithdraw.setText("");                
            }
            
            //System.out.print(amtWithdraw);
          // switchPanels(DEPOSIT2);
          //  panel = 1.1;
          if(agree==true){
              Withdraw w = new Withdraw(current_user.returnAcc(),amtWithdraw);
            JOptionPane.showMessageDialog(frame, df.format(amtWithdraw) +
                                " withdrawn from your account.");
            panel = 5;
            switchPanels(AskReceipt);
          }
            
        }
        
         //DEPOSIT PAGE
        else if(panel==2){
            Deposit d= new Deposit(current_user.returnAcc(),tranc.StringToDouble(amountDeposit.getText()));
            JOptionPane.showMessageDialog(frame, df.format(tranc.StringToDouble(amountDeposit.getText())) +
                                " deposited into your account.");
            
            //Progress bar
            panel =5;
            switchPanels(AskReceipt);            
        }
        
         //TRANSFER PAGE
        else if(panel==3){
            String card_no = accP1.getText()+"-"+accP2.getText()+"-"+accP3.getText()+"-"+accP4.getText();
            int match = 0;
            //System.out.println(totalUser+" in GUI_old");
            if(card_no.length()== 19){
                for(int i = 0;i<totalUser;i++){
                    System.out.println(user_card[i].getCardNo()+" in loop");
                    if(card_no.equals(user_card[i].getCardNo())){
                        System.out.println(user_card[i].getCardNo()+"in if");
                        recipient = user_card[i];
                        match = 1;
                        break;
                    }
                }
            }
            
            if(card_no.equals(current_user.getCardNo())){
                JOptionPane.showMessageDialog(null, "Please choose DEPOSIT to continue your transaction!\nPlease try again.");
                accP1.setText("");
                accP2.setText("");
                accP3.setText("");
                accP4.setText("");
                switchPanels(MENU);
                panel=0;
            }
            else if(match == 0){
                JOptionPane.showMessageDialog(null, "Invalid account number!\nPlease try again.");
                accP1.setText("");
                accP2.setText("");
                accP3.setText("");
                accP4.setText("");
            }
            else{
                switchPanels(TRANSFERAMT);
                panel =3.1;
            }
      //here check the existence of account
            /*if(success){
                displayCardNo.setText(card_no);
                switchPanels(TRANSFERAMT);
                panel = 3.1;
                
           /* }
            else{
             JOptionPane.showMessageDialog(null, "This account does not exist!\nPlease try again.");
                transferAcc.setText("");            
            }
            */
        }
        
        //ENTER TRANSFER AMOUNT
        else if(panel==3.1){
            Boolean agree=true;
            double amtTransfer = tranc.StringToDouble(amountTransfer.getText());
            if(amtTransfer>5000){
                agree = false;
                JOptionPane.showMessageDialog(null, "The maximum for tranfer amount is RM5000!");
                amountTransfer.setText("");                
            }
            if(amtTransfer>(current_user.returnBalance()-20)){
                agree = false;
                JOptionPane.showMessageDialog(null, "Insufficient funds in your account!Please try again.");
                amountTransfer.setText("");                
            }
          if(agree==true){
              Transfer t =new Transfer(current_user.returnAcc(),amtTransfer,recipient);
              t.getSummaryLine();
              displayCardNo.setText(recipient.getCardNo());
              displayCardHolder.setText(recipient.returnAcc().getAccHolder());
              displayTransferAmt.setText(df.format(recipient.returnBalance()));
              switchPanels(CONFIRMATION);
              panel = 3.2;
          }
       
        }
        
        else if(panel==3.2){
            //progress bar + do transfer here
            
            panel = 5;
            switchPanels(AskReceipt); 
            
            //switchPanels(AskReceipt);
        }    
         //BALANCE PAGE
        else if(panel==4){
            panel = 5;
            switchPanels(AskReceipt);
        }
        else if(panel==5){
            JOptionPane.showMessageDialog(null, "Kindly check your receipt.\n Thank you for visiting!");
            this.dispose();
            close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true); 
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void amountDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountDepositActionPerformed

    private void RM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM1ActionPerformed

    private void RM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM5ActionPerformed

    private void RM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM6ActionPerformed

    private void ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptActionPerformed
        //Print Receipt here
        JOptionPane.showMessageDialog(null, "Kindly check your receipt.\n Thank you for visiting!");
        this.dispose();
        close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true); 
    }//GEN-LAST:event_ReceiptActionPerformed

    private void NoReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoReceiptActionPerformed
        //Thanks for visiting....
        JOptionPane.showMessageDialog(null, "End Session\n Thank you for visiting!");
        this.dispose();
        close();
            ATM_Gui reload_ATM = new ATM_Gui();
            reload_ATM.setVisible(true);
    }//GEN-LAST:event_NoReceiptActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void RM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM2ActionPerformed

    private void amountTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTransferActionPerformed

    private void RM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM7ActionPerformed

    private void RM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM3ActionPerformed

    private void displayCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCardNoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_displayCardNoActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void accP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accP1ActionPerformed

    private void accP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accP2ActionPerformed

    private void accP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accP4ActionPerformed

    private void accP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accP3ActionPerformed

    private void displayCardHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCardHolderActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_displayCardHolderActionPerformed

    private void displayTransferAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTransferAmtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_displayTransferAmtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
      
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
        
        
        //</editor-fold>
      
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_old().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AskReceipt;
    private javax.swing.JPanel BALANCE;
    private javax.swing.JPanel CONFIRMATION;
    private javax.swing.JPanel DEPOSIT1;
    private javax.swing.JPanel Keypad;
    private javax.swing.JPanel MENU;
    private javax.swing.JRadioButton NoReceipt;
    private javax.swing.JTextField RM;
    private javax.swing.JTextField RM1;
    private javax.swing.JTextField RM2;
    private javax.swing.JTextField RM3;
    private javax.swing.JTextField RM5;
    private javax.swing.JTextField RM6;
    private javax.swing.JTextField RM7;
    private javax.swing.JRadioButton Receipt;
    private javax.swing.JPanel TRANSFERACC;
    private javax.swing.JPanel TRANSFERAMT;
    private javax.swing.JPanel TRANSFERAMT1;
    private javax.swing.JPanel WITHDRAW;
    private javax.swing.JTextField accP1;
    private javax.swing.JTextField accP2;
    private javax.swing.JTextField accP3;
    private javax.swing.JTextField accP4;
    private javax.swing.JTextField amountDeposit;
    private javax.swing.JTextField amountTransfer;
    private javax.swing.JTextField amountWithdraw;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnDoubleZero;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEmpty;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnZero;
    private javax.swing.JTextField displayCardHolder;
    private javax.swing.JTextField displayCardNo;
    private javax.swing.JTextField displayTransferAmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JTextField showAccNo;
    private javax.swing.JTextField showBalance;
    private javax.swing.JTextField titleDeposit;
    private javax.swing.JLabel titleTransfer;
    private javax.swing.JLabel titleTransfer1;
    private javax.swing.JTextField titleWithdraw;
    // End of variables declaration//GEN-END:variables
}
